# Generated by Django 5.2 on 2025-05-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='uploaded_at',
            new_name='upload_time',
        ),
    ]
