# Generated by Django 5.2 on 2025-05-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0002_rename_uploaded_at_imageupload_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='transcription',
            field=models.TextField(blank=True),
        ),
    ]
